export type PageData={title:string;en:string;intro:string;image:string;sections:{heading:string;body?:string;items?:{name:string;detail:string;price?:string}[]}[]};
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1800&q=85`;
export const pages:Record<string,PageData>={
 concept:{title:'私たちについて',en:'OUR STORY',intro:'料理を囲む時間が、今日を少し豊かにする。そんな食卓を吉祥寺から。',image:img('photo-1414235077428-338989a2e8c0'),sections:[{heading:'素材の声を、ひと皿に。',body:'武蔵野の契約農家から届く朝採れ野菜、豊洲で選ぶ魚介、国産小麦で毎朝打つパスタ。素材が一番おいしい瞬間を見極め、余計なものを足さずに仕立てます。'},{heading:'日常に根づくトラットリア',body:'記念日にも、何でもない火曜日にも。肩肘を張らず、何度でも帰ってきたくなる店であること。それが私たちの目指すレストランです。'}]},
 menu:{title:'メニュー',en:'MENU',intro:'季節と土地を映す、ヴェルデの料理。ランチからディナーまでお楽しみください。',image:img('photo-1473093295043-cdd812d0e601'),sections:[{heading:'ANTIPASTI',items:[{name:'本日の鮮魚のカルパッチョ',detail:'柑橘とハーブのヴィネグレット',price:'¥1,680'},{name:'有機野菜のバーニャカウダ',detail:'香ばしいアンチョビソース',price:'¥1,480'},{name:'パルマ産生ハムと季節の果実',detail:'24ヶ月熟成プロシュート',price:'¥1,760'}]},{heading:'PASTA',items:[{name:'タリアテッレ ボロネーゼ',detail:'黒毛和牛と香味野菜のラグー',price:'¥2,080'},{name:'季節野菜のペペロンチーノ',detail:'自家製スパゲッティ',price:'¥1,780'},{name:'渡り蟹のトマトクリーム',detail:'濃厚な旨みのリングイネ',price:'¥2,380'}]},{heading:'SECONDI',items:[{name:'本日の鮮魚 炭火焼き',detail:'焦がしレモンとケッパー',price:'¥2,680'},{name:'国産牛のタリアータ',detail:'ルッコラと熟成バルサミコ',price:'¥3,480'}]}]},
 lunch:{title:'ランチ',en:'LUNCH',intro:'陽の光が差し込む店内で、ゆったりと楽しむ昼のコース。',image:img('photo-1569058242253-92a9c755a0ec'),sections:[{heading:'PRANZO A',items:[{name:'パスタランチ',detail:'前菜盛り合わせ・選べるパスタ・自家製パン・カフェ',price:'¥2,200'}]},{heading:'PRANZO B',items:[{name:'季節のコース',detail:'前菜・パスタ・魚料理または肉料理・ドルチェ・カフェ',price:'¥3,800'}]},{heading:'週末のご案内',body:'土日祝はPRANZO Bとシェフおまかせコースをご用意します。お席は90分制ではありません。ごゆっくりお過ごしください。'}]},
 dinner:{title:'ディナー',en:'DINNER',intro:'薪火の香り、手打ちパスタ、グラスを満たすワイン。夜の食卓をゆっくりと。',image:img('photo-1515003197210-e0cd71810b5f'),sections:[{heading:'おすすめの一皿',items:[{name:'トリッパのトマト煮込み',detail:'じっくり煮込んだフィレンツェの郷土料理',price:'¥1,680'},{name:'鴨胸肉のロースト',detail:'赤ワインとカシスのソース',price:'¥3,280'},{name:'ティラミス ヴェルデ',detail:'マスカルポーネとエスプレッソ',price:'¥880'}]},{heading:'DINNER TIME',body:'17:30–22:00（L.O. 21:00）。アラカルトのほか、季節のおまかせコースも承ります。'}]},
 course:{title:'コース',en:'COURSE',intro:'旬をつなぐ一皿一皿。大切な夜のためのおまかせコース。',image:img('photo-1547592180-85f173990554'),sections:[{heading:'VERDE COURSE',items:[{name:'全6品',detail:'小さな前菜・冷前菜・温前菜・手打ちパスタ・メイン・ドルチェ',price:'¥6,600'}]},{heading:'CHEF’S COURSE',items:[{name:'全8品',detail:'その日の最良の食材で組み立てるシェフおまかせ',price:'¥9,900'}]},{heading:'記念日のお手伝い',body:'メッセージ付きドルチェプレート（¥1,100）をご用意できます。ご予約時にお申し付けください。'}]},
 wine:{title:'ワイン',en:'WINE',intro:'北から南まで、造り手の顔が見えるイタリアワインを中心に。',image:img('photo-1510812431401-41d2bd2722f3'),sections:[{heading:'GLASS WINE',items:[{name:'スプマンテ',detail:'ヴェネト／辛口',price:'¥900〜'},{name:'白ワイン',detail:'常時4種',price:'¥850〜'},{name:'赤ワイン',detail:'常時5種',price:'¥900〜'}]},{heading:'BOTTLE',body:'自然な栽培と醸造を大切にする小規模生産者を中心に、約80銘柄をセラーで保管しています。お好みとご予算に合わせてソムリエがご案内します。'}]},
 gallery:{title:'ギャラリー',en:'GALLERY',intro:'料理、ワイン、そして食卓を囲む風景。',image:img('photo-1552566626-52f8b828add9'),sections:[{heading:'THE TABLE',body:'季節ごとに変わる料理と、古木や真鍮をしつらえた落ち着きある空間。カウンター、テーブル、個室をご用意しています。'}]},
 chef:{title:'シェフ',en:'CHEF',intro:'イタリアの地方料理に学び、東京の旬を料理する。',image:img('photo-1577219491135-ce391730fb2c'),sections:[{heading:'料理長　高橋 悠',body:'東京のレストランで研鑽を積んだのち、イタリアへ。トスカーナとピエモンテの星付き店で4年間、土地に根ざした料理を学ぶ。2019年、TRATTORIA VERDEを開業。'},{heading:'MESSAGE',body:'気候も文化も違う日本で、イタリア料理をそのまま再現するのではなく、今ここにある素材の魅力をイタリアの知恵で引き出したいと考えています。'}]},
 news:{title:'お知らせ',en:'NEWS',intro:'季節のメニュー、営業日、イベントのご案内。',image:img('photo-1498579397066-22750a3cb424'),sections:[{heading:'2026.08.20',body:'秋の食材を使った新しいコースは9月4日より始まります。'},{heading:'2026.08.01',body:'夏季休業のお知らせ：8月18日（火）〜20日（木）はお休みをいただきます。'},{heading:'2026.07.12',body:'ワインメーカーズディナーのご予約受付を開始しました。'}]},
 access:{title:'店舗情報・アクセス',en:'ACCESS',intro:'吉祥寺駅から歩いて6分。中道通りの一本先、緑の扉が目印です。',image:img('photo-1517248135467-4c7edcad34c5'),sections:[{heading:'TRATTORIA VERDE',items:[{name:'住所',detail:'〒180-0004 東京都武蔵野市吉祥寺本町2-00-0'},{name:'電話',detail:'0422-00-0000'},{name:'営業時間',detail:'Lunch 11:30–15:00 / Dinner 17:30–22:00'},{name:'定休日',detail:'火曜日（祝日の場合は翌日）'},{name:'アクセス',detail:'JR・京王井の頭線 吉祥寺駅 北口より徒歩6分'}]},{heading:'お車でお越しの方へ',body:'専用駐車場はございません。近隣のコインパーキングをご利用ください。'}]},
 reservation:{title:'ご予約',en:'RESERVATION',intro:'オンラインまたはお電話で承ります。皆さまをお迎えできることを楽しみにしています。',image:img('photo-1559339352-11d035aa65de'),sections:[{heading:'ONLINE RESERVATION',body:'ご希望日の60日前から当日10時まで受け付けています。5名様以上、個室、貸切のご相談はお電話ください。'},{heading:'TEL 0422-00-0000',body:'受付時間 10:30–21:00（火曜を除く）'}]},
 'private-dining':{title:'個室・貸切',en:'PRIVATE DINING',intro:'ご家族の集まりから、小さなパーティーまで。',image:img('photo-1560624052-449f5ddf0c31'),sections:[{heading:'PRIVATE ROOM',items:[{name:'個室',detail:'4〜8名様／扉付きの落ち着いた空間',price:'室料 ¥3,300'}]},{heading:'RESTAURANT BUYOUT',items:[{name:'店舗貸切',detail:'着席20〜36名様／立食最大45名様',price:'お一人様 ¥8,800〜'}]},{heading:'ご相談ください',body:'ご予算、料理、ワイン、アレルギー、装花など、ご用途に合わせて担当者がご提案します。'}]},
 recruit:{title:'採用情報',en:'RECRUIT',intro:'料理と人が好きな仲間を募集しています。',image:img('photo-1556910103-1c02745aae4d'),sections:[{heading:'募集中のポジション',items:[{name:'キッチンスタッフ',detail:'正社員／経験者優遇・未経験可'},{name:'サービススタッフ',detail:'正社員・アルバイト／週2日から'},{name:'パティシエ',detail:'正社員／製菓経験2年以上'}]},{heading:'働く環境',body:'生産者訪問、ワイン勉強会、イタリア研修制度があります。まずは履歴書をrecruit@example.comへお送りください。'}]},
 faq:{title:'よくあるご質問',en:'FAQ',intro:'ご予約やご来店について、よくいただくご質問をまとめました。',image:img('photo-1559329007-40df8a9345d8'),sections:[{heading:'お子様のご利用について',body:'ランチは年齢を問わずご利用いただけます。ディナーは小学生以上のお子様からご案内しています。個室は年齢制限なくご利用いただけます。'},{heading:'アレルギー対応はできますか？',body:'可能な範囲で対応します。ご予約時に対象食材と程度をお知らせください。'},{heading:'ドレスコードはありますか？',body:'特別なドレスコードはありません。香りの強い香水はお控えください。'},{heading:'キャンセルについて',body:'当日キャンセルはコース料金の100%、前日は50%を申し受けます。'}]}
};
export const nav=[['concept','私たちについて'],['menu','メニュー'],['course','コース'],['wine','ワイン'],['access','店舗情報']];
